# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='car',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
